#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Keepalive Script Generated by Keepalive Gen
-------------------------------------------
Features:
- SOCKS5 Proxy Check (via curl)
- Log Rotation (Size based)
- Randomized Intervals
- Graceful Error Handling
"""

import sys
import time
import random
import logging
import os
import subprocess
from logging.handlers import RotatingFileHandler

# ================= Configuration =================
# Ports to check (SOCKS5)
PORTS = [10001,10002]

# Logging Configuration
LOG_DIR = "/var/log/keepalive/"
LOG_FILE = os.path.join(LOG_DIR, "keepalive.log")

# Rotation: 5MB per file, keep 5 backups
MAX_BYTES = 5242880 
BACKUP_COUNT = 5

# Check Interval (Seconds)
MIN_INTERVAL = 120
MAX_INTERVAL = 180

# Target URL to check connectivity
TARGET_URL = "https://www.google.com"
# =================================================

def setup_logging():
    """Configures logging with rotation and console output."""
    if not os.path.exists(LOG_DIR):
        try:
            os.makedirs(LOG_DIR)
        except PermissionError:
            print(f"CRITICAL: Cannot create log directory {LOG_DIR}. Run with sudo?")
            sys.exit(1)

    logger = logging.getLogger("Keepalive")
    logger.setLevel(logging.INFO)

    # File Handler with Rotation
    try:
        file_handler = RotatingFileHandler(
            LOG_FILE, maxBytes=MAX_BYTES, backupCount=BACKUP_COUNT, encoding='utf-8'
        )
        file_formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
        file_handler.setFormatter(file_formatter)
        logger.addHandler(file_handler)
    except PermissionError:
        print(f"CRITICAL: Cannot write to {LOG_FILE}. Check permissions.")
        sys.exit(1)

    # Console Handler (Stdout)
    console_handler = logging.StreamHandler()
    console_formatter = logging.Formatter('%(asctime)s - %(message)s')
    console_handler.setFormatter(console_formatter)
    logger.addHandler(console_handler)

    return logger

def check_port(port, logger):
    """Checks a specific port using curl through SOCKS5."""
    proxy = f"socks5://127.0.0.1:{port}"
    
    # We use subprocess with curl for reliability similar to the original shell script
    cmd = [
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "--connect-timeout", "10",
		"-I",
        "-x", proxy,
        TARGET_URL
    ]
    
    try:
        # Run curl command
        result = subprocess.run(cmd, capture_output=True, text=True)
        code = result.stdout.strip()
        
        if code == "200":
            logger.info(f" -> Port {port}: Success! (Status: 200)")
            return True
        else:
            logger.warning(f" -> Port {port}: Failed! (Status: {code})")
            return False
            
    except Exception as e:
        logger.error(f" -> Port {port}: Execution Error - {str(e)}")
        return False

def main():
    logger = setup_logging()
    logger.info("=== Starting Keepalive Service ===")
    logger.info(f"Monitoring Ports: {PORTS}")
    logger.info(f"Log Path: {LOG_FILE}")

    try:
        while True:
            cycle_start = time.time()
            logger.info("--- Starting Check Cycle ---")
            
            for port in PORTS:
                logger.info(f"Checking port {port}...")
                check_port(port, logger)
                # Small pause between ports to prevent CPU spikes or race conditions
                time.sleep(1)

            # Calculate sleep time
            sleep_duration = random.uniform(MIN_INTERVAL, MAX_INTERVAL)
            next_run = time.strftime('%H:%M:%S', time.localtime(time.time() + sleep_duration))
            
            logger.info(f"Cycle finished. Sleeping for {sleep_duration:.1f}s. Next run at {next_run}.")
            time.sleep(sleep_duration)

    except KeyboardInterrupt:
        logger.info("=== Service Stopped by User ===")
    except Exception as e:
        logger.critical(f"Unexpected Crash: {e}", exc_info=True)

if __name__ == "__main__":
    main()
